apiVersion: v1
kind: Service
metadata:
  name: akkahttp-service
  labels:
    app: akkaHttpApp-Service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30002
  selector:
    app: akkaHttpApp