format_version: 9
pipelines:
  akkaHttpPipelineYaml:
    group: defaultGroup
    materials:
      gitRepo:
        git: https://github.com/Harisankar-R/akkaHttp
        branch: master
    stages:
      - test:
          jobs:
            run-unit-test:
              tasks:
                - exec:
                    command: sbt
                    arguments:
                      - test
      - build:
          jobs:
            build-jar:
              artifacts:
                - build:
                    source: target/scala-2.12/akka-http-apis.jar
                    destination: ""
              tasks:
                - exec:
                    command: sbt
                    arguments:
                      - assembly
      - dockerize:
          jobs:
            dockerize-and-push-to-local:
              tasks:
                - fetch:
                    is_file: true
                    source: akka-http-apis.jar
                    destination: ""
                    pipeline: akkaHttpPipelineYaml
                    stage: build
                    job: build-jar
                    artifact_origin: gocd
                - exec:
                    command: docker-compose
                    arguments:
                      - build
      - run-kubernetes:
          jobs:
            run-k8-depolyment:
              tasks:
                - exec:
                    command: kubectl
                    arguments:
                      - create
                      - -f
                      - akkahttp-deployment.yml
            run-k8-service:
              tasks:
                - exec:
                    command: kubectl
                    arguments:
                      - create
                      - -f
                      - akkahttp-service.yml