format_version: 9
pipelines:
  akkaHttpBuild:
    group: defaultGroup
    materials:
      gitRepo:
        git: https://github.com/Harisankar-R/akkaHttp
        branch: master
    stages:
      - test:
          jobs:
            run-unit-test:
              tasks:
                - exec:
                    command: sbt
                    arguments:
                      - test
      - build:
          jobs:
            build-jar:
              artifacts:
                - build:
                    source: target/scala-2.12/akka-http-apis.jar
                    destination: ""
              tasks:
                - exec:
                    command: sbt
                    arguments:
                      - clean
                      - assembly
      - dockerize:
          jobs:
            dockerize-and-push-to-local:
              artifacts:
                - build:
                    source: akkahttp-deployment.yml
                    destination: ""
                - build:
                    source: akkahttp-service.yml
                    destination: ""
              tasks:
                - exec:
                    command: sbt
                    arguments:
                      - docker:publishLocal
  akkaHttpDeploy:
    group: defaultGroup
    materials:
      akkaHttpBuild:
        ignore_for_scheduling: false
        pipeline: akkaHttpBuild
        stage: dockerize
    stages:
      - run-kubernetes:
          jobs:
            run-k8-depolyment:
              tasks:
                - fetch:
                    is_file: true
                    source: akkahttp-deployment.yml
                    destination: ""
                    pipeline: akkaHttpBuild
                    stage: dockerize
                    job: dockerize-and-push-to-local
                    artifact_origin: gocd
                - exec:
                    command: kubectl
                    arguments:
                      - create
                      - -f
                      - akkahttp-deployment.yml
            run-k8-service:
              tasks:
                - fetch:
                    is_file: true
                    source: akkahttp-service.yml
                    destination: ""
                    pipeline: akkaHttpBuild
                    stage: dockerize
                    job: dockerize-and-push-to-local
                    artifact_origin: gocd
                - exec:
                    command: kubectl
                    arguments:
                      - create
                      - -f
                      - akkahttp-service.yml